apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: pizzeria

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: nithishpavan/pizzeria-api:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        env:
        - name: PORT
          value: "5000"

        - name: NODE_ENV
          value: production

        - name: DB_HOST
          value: postgres

        - name: DB_PORT
          value: "5432"

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
