apiVersion: v1
kind: Secret

metadata:
  name: mail-secret
  namespace: pizzeria

type: Opaque

stringData:
  SMTP_HOST: sandbox.smtp.mailtrap.io
  SMTP_PORT: "2525"
  SMTP_USER: 1fec3c7791227c
  SMTP_PASSWORD: 462585dd50c9eb
  SMTP_FROM: "Nithish Pizzeria <no-reply@nithishpizzeria.com>"
